version: '3'

services:
  app:
    build:
      context: ./casino-gaming-front
    image: marionepomuceno/kanongaming-app
    entrypoint: dockerize -wait tcp://api:2002 -timeout 20s docker-entrypoint.sh npm start
    networks:
      - kanongaming-network
    tty: true
    container_name: app
    ports:
      - "2001:3000"
    depends_on: 
      - api

  api:
    build:
      context: ./casino-gaming-api
    image: marionepomuceno/kanongaming-api
    entrypoint: dockerize -wait tcp://db:1433 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - kanongaming-network
    tty: true
    container_name: api
    ports:
      - "2002:2002"
    depends_on: 
      - db
    

  db:
    build:
      context: ./casino-gaming-database
    image: marionepomuceno/kanongaming-database
    container_name: db
    restart: always
    tty: true
    expose:
      - "1433"
    networks:
      - kanongaming-network

networks:
  kanongaming-network:
    driver: bridge